import Vue from 'vue'
import Vuex from 'vuex'
import router from '../router'
import { db } from '../firebase'
import { auth } from '../firebase'

Vue.use(Vuex)

export default new Vuex.Store({

  state: {
    /* --   OLD doggies JSON SAMPLE -- */
    // {
    //   "customerId": 1,
    //   "doggie": {
    //     "name": "andi",
    //     "breed": ["bichón maltés"],
    //     "mood": "Simpático jugetón"
    //   },
    //   "owner": [
    //     {
    //       "name": "lina",
    //       "phone": 696620723
    //     }
    //   ],
    //   "comment": "Es superbueno :)",
    //   "dates": [
    //     {
    //       "date": "2017-03-06T00:00:00-0400",
    //       "groom": null,
    //       "price": 28
    //     }
    //   ]
    // },
    /* -- "Clients" Data -- */
    // all "customers" data
    customers: [],

    // a specific single "client"
    client: {
      name: '',
      breed: '',
      mood: '',
      owner: '',
      ownerPhone: 0,
      guardian: '',
      guardianPhone: 0,
      comment: ''
    },

    /* -- "Users" Data -- */
    user: null,
    error: null
  },

  mutations: {
    // 1. SET all "customers" data from Firebase´s Firestore DB
    setCustomers(state, payload) {
      state.customers = payload
    },

    // 2. SET single "customer" (client) data from Firebase´s Firestore DB
    setClient(state, payload) {
      state.client = payload
    },

    // 5. DELETE a single "customer" (client) data into Firebase´s Firestore DB
    setClientRemoved(state, payload) {
      state.customers = state.customers.filter(client => client.id !== payload)
    },

    /* -- "Users" Data -- */

    // a. SET single user data from Firebase´s Auth
    setUser(state, payload) {
      state.user = payload
    },

    // a. SET (catch) Errors from Firebase´s Auth
    setError(state, payload) {
      state.error = payload
    },
  },

  actions: {
    // 1. GET all "customers" data from Firebase´s Firestore DB
    getCustomers({commit}) {
      const customers = []
      db.collection('customers')
        .get() // all Documents of a Firestore DB Collection
        .then(res => {
          res.forEach(document => {
            console.log(`
              ${document.id}
              ${document.data().name}
              --- 👌 ---
            `)
            let customer = document.data()
            customer.id = document.id
            customers.push(customer)
          })

          commit('setCustomers', customers)
        })
    },

    // 2. GET single "customer" (client) data from Firebase´s Firestore DB
    getClient({commit}, clientId) {
      db.collection('customers')
        .doc(clientId) // a specific single Document of a Firestore DB Collection 
        .get()
        .then(document => {
          console.log(`
              ${document.id}
              ${document.data().name}
              ----- 🐶 -----
            `)
          let client = document.data()
          client.id = document.id

          commit('setClient', client)
        })
    },

    // 3. EDIT single "customer" (client) data from Firebase´s Firestore DB
    editClient({commit}, editedClient) {
      db.collection('customers')
        .doc(editedClient.id) // a specific single Document of a Firestore DB Collection
        .update({
          name: editedClient.name,
          breed: editedClient.breed,
          mood: editedClient.mood,
          owner: editedClient.owner,
          ownerPhone: editedClient.ownerPhone,
          guardian: editedClient.guardian,
          guardianPhone: editedClient.guardianPhone,
          comment: editedClient.comment,
        })
        .then(() => {
          console.log(`
              Cliente "${editedClient.name}" editado
              ---- 🔄 ----
            `)
          router.push('/')
        })
    },

    // 4. ADD new single "customer" (client) data into Firebase´s Firestore DB
    addClient({commit}, addedClient) {
      db.collection('customers')
        .add({
          name: addedClient.name,
          breed: addedClient.breed,
          mood: addedClient.mood,
          owner: addedClient.owner,
          ownerPhone: addedClient.ownerPhone,
          guardian: addedClient.guardian,
          guardianPhone: addedClient.guardianPhone,
          comment: addedClient.comment,
        }) // add new single Document with autogenerated ID into Firestore DB Collection
        // .doc().set(client.id) // add new single Document with custom ID passed as param into Firestore DB Collection
        .then(doc => {
          console.log(`
            Nuevo cliente "${doc.name}"
            ---- ✨ ----
          `)
          router.push('/')
        })
    },

    // 5. DELETE a single "customer" (client) data into Firebase´s Firestore DB
    removeClient({commit, dispatch}, deletedClientId) {
      db.collection('customers')
        .doc(deletedClientId)
        .delete()
        .then(() => {
          console.log(`
            Cliente "${deletedClientId}" eliminado
            ---- 🔥 ----
          `)
          // We need reload "Home" page to update "customers" list cause Firestore is not RealTimeDB:
          // (option 1) with "dispatch" method but it´s not the perfect way cause need another query to server
          // dispatch('getCustomers')
          // (option 2) with "dispatch" method but it´s not the perfect way cause need another query to server
          commit('setClientRemoved', deletedClientId)
        })
    },

    /* -- "Users" Data -- */

    // a. SET new "user" in Firebase´s Auth DB
    createUser({commit}, userData) {
      auth.createUserWithEmailAndPassword(userData.email, userData.password) // just only two arguments accepted
          .then(res => {
            console.log(`
              Nuevo usuario: "${res.user.email}"
              ----- ✨ -----
            `)
            console.log(res) // all "user" obj data (res.user...)
            const userCreated = {
              email: res.user.email,
              uid: res.user.uid,
            }
            commit('setUser', userCreated)
            router.push('/')
          })
          .catch(err => {
            console.log(`
              Error usuario: "${err}"
              ---- 🔥 ----
            `)
            commit('setError', err)
          })
    },

    // b. GET exist "user" in Firebase´s Auth DB
    loginUser({commit}, userData) {
      auth.signInWithEmailAndPassword(userData.email, userData.password)
          .then(res => {
            console.log(res) // all "user" obj data (res.user...)
            const userLoggedIn = {
              email: res.user.email,
              uid: res.user.uid,
            }
            commit('setUser', userLoggedIn)
            router.push('/')
          })
          .catch(err => {
            console.log(`
              Error usuario: "${err}"
              ---- 🔥 ----
            `)
            commit('setError', err)
          })
    },

    // c. CLOSE "user" session in store
    logoutUser({commit}) {
      auth.signOut()
          .then(() => {
            console.log(`
              User signOut
              --- 🚪🏃 ---
            `)
            router.push('/login')
          })
    },

    // d. UPDATE "user" info after login to allow his data across platform
    isUserAuth({commit}, userAuth) {
      commit('setUser', userAuth)
    }

  },

  /* "getters" props are watchers to allow "state" info across webapp cause use "state" directly is not recommended */
  getters: {
    isUserLoggedIn(state) {
      return !!state.user
    }
    /* -- code above is equal than the following one -- */
    // isUserLoggedIn(state) {
    //   if (state.user === null) {
    //     return false
    //   } else {
    //     return true
    //   }
    // }
  },

  modules: {
  }
})
